version: '3'

services:
  pytorch_cyclegan_and_pix2pix:
    # this is for allowing to run in detached mode
    tty: true
    stdin_open: true
    build:
      context: ./
      dockerfile: docker/Dockerfile
    image: foldedai/pytorch_cyclegan_and_pix2pix
    container_name: pytorch_cyclegan_and_pix2pix
    ports:
      - "8097"
    volumes:
      - /var/log/pytorch_cyclegan_and_pix2pix:/var/log/pytorch_cyclegan_and_pix2pix
      - ./:/pytorch_cyclegan_and_pix2pix
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [ gpu ]
      restart_policy:
        condition: on-failure
